### ISSUE TITLE
Can not build! (for 17.40)

### ISSUE THREAD

**Issue by darrmining** [ktsol/dwarfing#3]
hi, I attempted to run your amdgpu-mod and got this output:

BUILDING new amdgpu.ko file
Patch file /usr/src/amdgpu-17.40-483984/amd/powerplay/smumgr/polaris10_smc.c
patching file /usr/src/amdgpu-17.40-483984/amd/powerplay/smumgr/polaris10_smc.c
Hunk #3 succeeded at 780 (offset 4 lines).
File patched: /usr/src/amdgpu-17.40-483984/amd/powerplay/smumgr/polaris10_smc.c
Patch file /usr/src/amdgpu-17.40-483984/amd/powerplay/hwmgr/smu7_hwmgr.c
patching file /usr/src/amdgpu-17.40-483984/amd/powerplay/hwmgr/smu7_hwmgr.c
Hunk #1 succeeded at 4403 (offset 24 lines).
File patched: /usr/src/amdgpu-17.40-483984/amd/powerplay/hwmgr/smu7_hwmgr.c
make: Entering directory '/usr/src/linux-headers-4.11.0-kfd-compute-rocm-rel-1.6-180'
  LD      /usr/src/amdgpu-17.40-483984/built-in.o
  LD      /usr/src/amdgpu-17.40-483984/amd/amdgpu/built-in.o
  CC [M]  /usr/src/amdgpu-17.40-483984/amd/amdgpu/amdgpu_drv.o
In file included from /usr/src/amdgpu-17.40-483984/amd/amdgpu/../include/../backport/backport.h:14:0,
                 from <command-line>:0:
/usr/src/amdgpu-17.40-483984/include/kcl/kcl_reservation.h: In function ‘kcl_reservation_object_copy_fences’:
/usr/src/amdgpu-17.40-483984/include/kcl/kcl_reservation.h:95:9: error: implicit declaration of function ‘reservation_object_copy_fences’ [-Werror=implicit-function-declaration]
  return reservation_object_copy_fences(dst, src);
         ^
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/usr/src/amdgpu-17.40-483984/amd/amdgpu/amdgpu_drv.o' failed
make[2]: *** [/usr/src/amdgpu-17.40-483984/amd/amdgpu/amdgpu_drv.o] Error 1
scripts/Makefile.build:553: recipe for target '/usr/src/amdgpu-17.40-483984/amd/amdgpu' failed
make[1]: *** [/usr/src/amdgpu-17.40-483984/amd/amdgpu] Error 2
Makefile:1492: recipe for target '_module_/usr/src/amdgpu-17.40-483984' failed
make: *** [_module_/usr/src/amdgpu-17.40-483984] Error 2
make: Leaving directory '/usr/src/linux-headers-4.11.0-kfd-compute-rocm-rel-1.6-180'
/home/james/Downloads/dwarfing-master

**Comment by rumatoest** [comment]
Hello.

It should work only for Ubuntu LTS with non HWE kernel.

Could you try to build project from /usr/src/amdgpu-17.40-483984/ without my script?

**Comment by rumatoest** [comment]
BTW I've never tested it with amdgpu 17.40 only 17.30-465504
