### ISSUE TITLE
no longer works with 4.15-rc

### ISSUE THREAD

**Issue by Macribit** [ktsol/dwarfing#4]
hi sorry to bug you can you update to 4.15-rc it doesn't work I guess file names changed.

**Comment by rumatoest** [comment]
I just do not want, because on my setup everything work fine. 
It will be very exciting if someone submits pull request with fixes.

**Comment by Macribit** [comment]
but with linux 4.15 for me there is an increase on OpenCL performance there are some fixes that makes mining run faster

**Comment by rumatoest** [comment]
You can propose your own patch

**Comment by Macribit** [comment]
Now that I look into. It seems that at some point of RC one file was renamed and merged into one, but that was reverted, I think. Will check back. I'am running rc9, rc8 changed files names and I couldn't patch. I'll try 4.15 final and report back. I'm looking into this I can propose a patch but I need help not sure what I'm doing here.

**Comment by Macribit** [comment]
yes 4.15 reverted those changes and looks green. I'll look further to see if on 4.16RC there is new changes and see if I can make a patch. But there's no point if the changes don't make to final.

**Comment by rumatoest** [comment]
The main problem I faced is that even newest amdgpu driver is no compatible with kernels  => 4.11 - it can not compile kernel module for 16.04
This patch may work only if you are able properly install amdgpu drivers on latest kernel available in ubuntu repository.
